/*
 *  Copyright 2020 generated by Joerg Hohwiller.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.teavm.classlib.java.time.zone;

import java.util.Map;
import org.teavm.classlib.java.time.zone.TZoneOffsetTransitionRule.TimeDefinition;

final class TTzdbInternalEtc {
    static void init(Map<String, TZoneRules> map) {
        map.put("Etc/GMT", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/GMT+0", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/GMT+1", new TStandardZoneRules(new long[] {}, new int[] {-3600}, new long[] {}, new int[] {-3600}));
        map.put("Etc/GMT+10", new TStandardZoneRules(new long[] {}, new int[] {-36000}, new long[] {}, new int[] {-36000}));
        map.put("Etc/GMT+11", new TStandardZoneRules(new long[] {}, new int[] {-39600}, new long[] {}, new int[] {-39600}));
        map.put("Etc/GMT+12", new TStandardZoneRules(new long[] {}, new int[] {-43200}, new long[] {}, new int[] {-43200}));
        map.put("Etc/GMT+2", new TStandardZoneRules(new long[] {}, new int[] {-7200}, new long[] {}, new int[] {-7200}));
        map.put("Etc/GMT+3", new TStandardZoneRules(new long[] {}, new int[] {-10800}, new long[] {}, new int[] {-10800}));
        map.put("Etc/GMT+4", new TStandardZoneRules(new long[] {}, new int[] {-14400}, new long[] {}, new int[] {-14400}));
        map.put("Etc/GMT+5", new TStandardZoneRules(new long[] {}, new int[] {-18000}, new long[] {}, new int[] {-18000}));
        map.put("Etc/GMT+6", new TStandardZoneRules(new long[] {}, new int[] {-21600}, new long[] {}, new int[] {-21600}));
        map.put("Etc/GMT+7", new TStandardZoneRules(new long[] {}, new int[] {-25200}, new long[] {}, new int[] {-25200}));
        map.put("Etc/GMT+8", new TStandardZoneRules(new long[] {}, new int[] {-28800}, new long[] {}, new int[] {-28800}));
        map.put("Etc/GMT+9", new TStandardZoneRules(new long[] {}, new int[] {-32400}, new long[] {}, new int[] {-32400}));
        map.put("Etc/GMT-0", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/GMT-1", new TStandardZoneRules(new long[] {}, new int[] {3600}, new long[] {}, new int[] {3600}));
        map.put("Etc/GMT-10", new TStandardZoneRules(new long[] {}, new int[] {36000}, new long[] {}, new int[] {36000}));
        map.put("Etc/GMT-11", new TStandardZoneRules(new long[] {}, new int[] {39600}, new long[] {}, new int[] {39600}));
        map.put("Etc/GMT-12", new TStandardZoneRules(new long[] {}, new int[] {43200}, new long[] {}, new int[] {43200}));
        map.put("Etc/GMT-13", new TStandardZoneRules(new long[] {}, new int[] {46800}, new long[] {}, new int[] {46800}));
        map.put("Etc/GMT-14", new TStandardZoneRules(new long[] {}, new int[] {50400}, new long[] {}, new int[] {50400}));
        map.put("Etc/GMT-2", new TStandardZoneRules(new long[] {}, new int[] {7200}, new long[] {}, new int[] {7200}));
        map.put("Etc/GMT-3", new TStandardZoneRules(new long[] {}, new int[] {10800}, new long[] {}, new int[] {10800}));
        map.put("Etc/GMT-4", new TStandardZoneRules(new long[] {}, new int[] {14400}, new long[] {}, new int[] {14400}));
        map.put("Etc/GMT-5", new TStandardZoneRules(new long[] {}, new int[] {18000}, new long[] {}, new int[] {18000}));
        map.put("Etc/GMT-6", new TStandardZoneRules(new long[] {}, new int[] {21600}, new long[] {}, new int[] {21600}));
        map.put("Etc/GMT-7", new TStandardZoneRules(new long[] {}, new int[] {25200}, new long[] {}, new int[] {25200}));
        map.put("Etc/GMT-8", new TStandardZoneRules(new long[] {}, new int[] {28800}, new long[] {}, new int[] {28800}));
        map.put("Etc/GMT-9", new TStandardZoneRules(new long[] {}, new int[] {32400}, new long[] {}, new int[] {32400}));
        map.put("Etc/GMT0", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/Greenwich", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/UCT", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/UTC", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/Universal", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
        map.put("Etc/Zulu", new TStandardZoneRules(new long[] {}, new int[] {0}, new long[] {}, new int[] {0}));
    }
}
