/*
 *  Copyright 2020 generated by Joerg Hohwiller.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.teavm.classlib.java.time.zone;

import java.util.Map;
import org.teavm.classlib.java.time.zone.TZoneOffsetTransitionRule.TimeDefinition;

final class TTzdbInternalIndian {
    static void init(Map<String, TZoneRules> map) {
        map.put("Indian/Antananarivo", new TStandardZoneRules(new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}, new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}));
        map.put("Indian/Chagos", new TStandardZoneRules(new long[] {-1988167780L, 820436400L}, new int[] {17380, 18000, 21600}, new long[] {-1988167780L, 820436400L}, new int[] {17380, 18000, 21600}));
        map.put("Indian/Christmas", new TStandardZoneRules(new long[] {-2364102172L}, new int[] {25372, 25200}, new long[] {-2364102172L}, new int[] {25372, 25200}));
        map.put("Indian/Cocos", new TStandardZoneRules(new long[] {-2209012060L}, new int[] {23260, 23400}, new long[] {-2209012060L}, new int[] {23260, 23400}));
        map.put("Indian/Comoro", new TStandardZoneRules(new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}, new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}));
        map.put("Indian/Kerguelen", new TStandardZoneRules(new long[] {-631152000L}, new int[] {0, 18000}, new long[] {-631152000L}, new int[] {0, 18000}));
        map.put("Indian/Mahe", new TStandardZoneRules(new long[] {-2006653308L}, new int[] {13308, 14400}, new long[] {-2006653308L}, new int[] {13308, 14400}));
        map.put("Indian/Maldives", new TStandardZoneRules(new long[] {-315636840L}, new int[] {17640, 18000}, new long[] {-315636840L}, new int[] {17640, 18000}));
        map.put("Indian/Mauritius", new TStandardZoneRules(new long[] {-1988164200L}, new int[] {13800, 14400}, new long[] {-1988164200L, 403041600L, 417034800L, 1224972000L, 1238274000L}, new int[] {13800, 14400, 18000, 14400, 18000, 14400}));
        map.put("Indian/Mayotte", new TStandardZoneRules(new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}, new long[] {-1309746436L, -1262314800L, -946780200L, -315629100L}, new int[] {8836, 10800, 9000, 9900, 10800}));
        map.put("Indian/Reunion", new TStandardZoneRules(new long[] {-1848886912L}, new int[] {13312, 14400}, new long[] {-1848886912L}, new int[] {13312, 14400}));
    }
}
