/*
 *  Copyright 2026 Alexey Andreev.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.teavm.junit;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.function.Supplier;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.LongStream;
import java.util.stream.Stream;
import org.junit.jupiter.api.Named;
import org.junit.jupiter.params.provider.Arguments;

/**
 * Converts values produced by {@code @MethodSource} factory methods and {@code @FieldSource}
 * fields into argument rows. Never runs on the JVM: it's compiled into the test artifact by
 * TeaVM and called from code generated by {@link TestEntryPointTransformer}.
 */
final class JupiterArgumentsRuntime {
    private JupiterArgumentsRuntime() {
    }

    static Object[][] fromMethod(Object source, int parameterCount) {
        return toRows(source, parameterCount);
    }

    static Object[][] fromField(Object source, int parameterCount) {
        if (source instanceof Supplier<?>) {
            source = ((Supplier<?>) source).get();
        }
        return toRows(source, parameterCount);
    }

    private static Object[][] toRows(Object source, int parameterCount) {
        var rows = new ArrayList<Object[]>();
        if (source instanceof Stream<?>) {
            addAll(rows, ((Stream<?>) source).iterator());
        } else if (source instanceof IntStream) {
            for (var item : ((IntStream) source).toArray()) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof LongStream) {
            for (var item : ((LongStream) source).toArray()) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof DoubleStream) {
            for (var item : ((DoubleStream) source).toArray()) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof Iterable<?>) {
            addAll(rows, ((Iterable<?>) source).iterator());
        } else if (source instanceof Iterator<?>) {
            addAll(rows, (Iterator<?>) source);
        } else if (source instanceof Object[]) {
            for (var item : (Object[]) source) {
                rows.add(toRow(item));
            }
        } else if (source instanceof int[]) {
            for (var item : (int[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof long[]) {
            for (var item : (long[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof double[]) {
            for (var item : (double[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof float[]) {
            for (var item : (float[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof short[]) {
            for (var item : (short[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof byte[]) {
            for (var item : (byte[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof char[]) {
            for (var item : (char[]) source) {
                rows.add(new Object[] { item });
            }
        } else if (source instanceof boolean[]) {
            for (var item : (boolean[]) source) {
                rows.add(new Object[] { item });
            }
        } else {
            throw new IllegalArgumentException("Can't use " + (source != null ? source.getClass().getName() : "null")
                    + " as a source of arguments");
        }

        for (var i = 0; i < rows.size(); ++i) {
            var row = rows.get(i);
            if (row.length < parameterCount) {
                throw new IllegalArgumentException("Arguments #" + (i + 1) + " provide " + row.length
                        + " values, but " + parameterCount + " parameters are declared");
            }
            for (var j = 0; j < row.length; ++j) {
                if (row[j] instanceof Named<?>) {
                    row[j] = ((Named<?>) row[j]).getPayload();
                }
            }
        }
        return rows.toArray(new Object[0][]);
    }

    private static void addAll(List<Object[]> rows, Iterator<?> iterator) {
        while (iterator.hasNext()) {
            rows.add(toRow(iterator.next()));
        }
    }

    private static Object[] toRow(Object item) {
        if (item instanceof Arguments) {
            return ((Arguments) item).get().clone();
        }
        if (item instanceof Object[] && !item.getClass().getComponentType().isArray()) {
            return ((Object[]) item).clone();
        }
        return new Object[] { item };
    }
}
